import * as fs from 'fs/promises';
// --- GEMINI API CONFIGURATION ---
const apiKey        = process.env.GEMINI_API_KEY;
const apiUrl        =`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-09-2025:generateContent?key=${apiKey}`;
const KNOWLEDGE_FILE='KnowLedgeDataBase.json';

// --- GENERATION CONFIGURATION (1 CALL) ---
const TOTAL_ITEMS   = 25;    // NEW DESIRED TOTAL: 25

// Expected JSON structure for each item (NOW: an array of 25 objects)
const responseSchema= {
    type: 'ARRAY',
    items: {
        type: 'OBJECT',
        properties: {
            'name': { 'type': 'STRING', 'description': 'Name of the technology (e.g., React, MongoDB).' },
            'description': { 'type': 'STRING', 'description': 'Concise description of the technology.' },
            'date': { 'type': 'STRING', 'description': 'Year of creation/launch (e.g., "2013").' },
            'link': { 'type': 'STRING', 'description': 'Official URL or main documentation link.' },
            'tags': {
                'type':'ARRAY',
                'description':'Array of 3 to 5 strings that categorize the technology (e.g., "frontend","database","framework","programming language").',
                'items':{'type':'STRING'}
            }
        },
        'required': ['name','description','date','link','tags']
    }
};
/**
 * Asynchronously waits for a specified time.
 * @param {number} ms - Milliseconds to wait.
 */
const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));
/**
 * Function to generate knowledge in a single API call.
 * @returns {Promise<Array<Object>>} Array with the 25 new knowledge entries.
 */
async function generateNewKnowledge(existingKnowledge) {
    // List of existing names to prevent repetition (for inclusion in the prompt)
    const existingNames = existingKnowledge.map(item => item.name).join(', ');
    const systemPrompt = `You are a technology and programming language expert. Your task is to create ${TOTAL_ITEMS} new entries about different technologies (languages, frameworks, tools, databases, methodologies, etc.) using the same JSON structure. Ensure each entry is unique and relevant. The focus is on current and widely used terms in software development.`;
    // NEW userQuery: Focused on 25 items and avoiding existing names
    const userQuery = `Generate a list of ${TOTAL_ITEMS} new technologies. Strictly follow the JSON structure and the requirement of being an ARRAY with EXACTLY ${TOTAL_ITEMS} objects. Do not include the 5 initial technologies (Python, JavaScript, Java, C++, Ruby) and DO NOT use ANY of the following names: ${existingNames}.`;
    const payload = {
        contents: [{ parts: [{ text: userQuery }] }],
        systemInstruction: { parts: [{ text: systemPrompt }] },
        generationConfig: {
            responseMimeType: 'application/json',
            responseSchema: responseSchema
        }
    };

    let response;
    let retries = 0;
    const maxRetries = 5;

    while (retries < maxRetries) {
        try {
            response = await fetch(apiUrl, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(payload)
            });

            if (response.ok) {
                const result = await response.json();
                const jsonText = result.candidates?.[0]?.content?.parts?.[0]?.text;

                if (jsonText) {
                    try {
                        const newKnowledge = JSON.parse(jsonText);

                        if (Array.isArray(newKnowledge) && newKnowledge.length === TOTAL_ITEMS) {
                            console.log(`Success! ${TOTAL_ITEMS} new items generated by the API.`);
                            return newKnowledge;
                        } else {
                            // If the model didn't generate the exact number, we try again
                            throw new Error(`The returned array does not contain ${TOTAL_ITEMS} items. Found: ${Array.isArray(newKnowledge) ? newKnowledge.length : 0}`);
                        }
                    } catch (parseError) {
                        throw new Error('Malformed or incomplete JSON in the API response.');
                    }
                } else {
                    throw new Error('Empty API response or no textual content.');
                }
            } else {
                throw new Error(`API failure with status ${response.status}: ${response.statusText}`);
            }
        } catch (error) {
            retries++;
            if (retries < maxRetries) {
                const waitTime = Math.pow(2, retries) * 1000; // 2s, 4s, 8s, ...
                console.log(`Retrying in ${waitTime / 1000}s...`); // Added log for clarity
                await delay(waitTime);
            } else {
                throw new Error(`Failed to generate knowledge after several attempts: ${error.message}`);
            }
        }
    }
}


/**
 * Main function to execute the workflow.
 */
async function main() {
    // Check if the API key is present
    if (!apiKey) {
        console.error('\n❌ ERROR: The GEMINI_API_KEY environment variable is not defined.');
        console.log("Please create a '.env' file in the project root and define the key:");
        console.log('GEMINI_API_KEY="YOUR_KEY_HERE"');
        return;
    }
    try {
        // 1. Load the existing knowledge base
        let existingKnowledge = [];
        try {
            const data = await fs.readFile(KNOWLEDGE_FILE, 'utf-8');
            existingKnowledge = JSON.parse(data);
            // Renaming the keys to English for internal consistency based on your previous requests
            existingKnowledge = existingKnowledge.map(item => ({
                name: item.name || item.nome,
                description: item.description || item.descricao,
                date: item.date || item.date,
                link: item.link || item.link,
                tags: item.tags
            }));
            console.log(`Initial knowledge base loaded. Total items: ${existingKnowledge.length}`);
        } catch (e) {
            if (e.code === 'ENOENT') {
                console.log(`The file ${KNOWLEDGE_FILE} was not found. Starting with an empty base.`);
            } else {
                throw new Error(`Error reading/parsing ${KNOWLEDGE_FILE}: ${e.message}`);
            }
        }
        // 2. Generate the 25 new entries (passing the existing base to the prompt)
        console.log('Expanding KnowLedge DataBase!');
        const newKnowledge = await generateNewKnowledge(existingKnowledge);
        // 3. Combine the bases
        const totalKnowledge = [...existingKnowledge, ...newKnowledge];
        console.log(`Combined knowledge base. Final total items: ${totalKnowledge.length}`);
        // 4. Save the new base to the file
        await fs.writeFile(KNOWLEDGE_FILE, JSON.stringify(totalKnowledge, null, 2), 'utf-8');
        console.log('\n🎉 SUCCESS!');
        console.log(`The file '${KNOWLEDGE_FILE}' has been updated with ${totalKnowledge.length} items.`);
    } catch (error) {
        console.error('\n❌ FATAL ERROR:', error.message);
        console.log('Please check that your API key is correct and that you have connectivity.');
    }
}
main( );
