let data    = [{title:              'Girl with a Pearl Earring',
                year:               '1665',
                technique:          'oil on canvas',
                size:               '44.5cm × 39cm',
                description:        'A young woman with a mysterious gaze, wearing a large pearl earring.',
                museum:             'Mauritshuis, The Hague',
                acquisitionDate:    'Acquisition: 1822',
                exhibitions:        'Exhibitions: Vermeer and the Delft School & The Golden Age of Dutch Painting',
                restorations:       'Restorations: 1991 & 2018',
                symbolism:          'Symbolism: the pearl earring may symbolize wealth, purity, and the passage of youth.',
                tags:               'vermeer dutch delft',
                link:               'https://en.wikipedia.org/wiki/Girl_with_a_Pearl_Earring',
                image:              'https://www.mauritshuis.nl/en/our-collection/artworks/670-girl-with-a-pearl-earring/'},
               {title:              'View of Delft',
                year:               '1660',
                technique:          'oil on canvas',
                size:               '98.5cm × 133cm',
                description:        "A panoramic view of Delft, Vermeer's hometown, showcasing its architecture and daily life.",
                museum:             'Mauritshuis, The Hague',
                acquisitionDate:    'Acquisition: 1822',
                exhibitions:        'Exhibition: Dutch Golden Age Paintings',
                restorations:       'Restoration: 1970',
                symbolism:          "Symbolism: the view may represent Vermeer's pride in his hometown and the Dutch Golden Age.",
                tags:               'vermeer dutch delft',
                link:               'https://en.wikipedia.org/wiki/View_of_Delft',
                image:              'https://www.mauritshuis.nl/en/our-collection/artworks/92-view-of-delft/'},
               {title:              'The Milkmaid',
                year:               '1658',
                technique:          'oil on canvas',
                size:               '45.8cm × 41cm',
                description:        'A simple domestic scene of a young woman pouring milk into a pitcher.',
                museum:             'Rijksmuseum, Amsterdam',
                acquisitionDate:    'Acquisition: 1817',
                exhibitions:        'Exhibition: Dutch Masters',
                restorations:       'Restoration: 1994',
                symbolism:          'Symbolism: the milkmaid may symbolize everyday life, simplicity, and the importance of light.',
                tags:               'vermeer dutch delft',
                link:               'https://en.wikipedia.org/wiki/The_Milkmaid_(Vermeer)',
                image:              'https://www.rijksmuseum.nl/en/collection/SK-A-2344'},
               {title:              'The Geographer',
                year:               '1669',
                technique:          'oil on canvas',
                size:               '51.5cm × 45.5cm',
                description:        'A man studying a globe, representing intellectual curiosity and exploration.',
                museum:             'Louvre, Paris',
                acquisitionDate:    'Acquisition: 1817',
                exhibitions:        'Exhibitions: Vermeer and the Delft School & The Golden Age of Dutch Painting',
                restorations:       'Restorations: 1991 & 2018',
                symbolism:          'Symbolism: the globe may symbolize knowledge, discovery, and the interconnectedness of the world.',
                tags:               'vermeer dutch delft',
                link:               'https://en.wikipedia.org/wiki/The_Geographer',
                image:              'http://www.essentialvermeer.com/catalogue/geographer.html'},
               {title:              'Woman Reading a Letter',
                year:               '1665',
                technique:          'oil on canvas',
                size:               '77.5cm × 65cm',
                description:        'A woman absorbed in reading a letter, conveying a sense of intimacy and contemplation.',
                museum:             'National Gallery of Art, Washington, D.C.',
                acquisitionDate:    'Acquisition: 1962',
                exhibitions:        'Exhibition: Vermeer – The Master of Delft',
                restorations:       'Restoration: 1992',
                symbolism:          'Symbolism: the letter may symbolize communication, longing, and the power of words.',
                tags:               'vermeer dutch delft',
                link:               'https://en.wikipedia.org/wiki/Woman_Reading_a_Letter_(Vermeer)',
                image:              'https://www.getty.edu/art/exhibitions/vermeer/'}];
