let vermeer = [{title:              'Girl with a Pearl Earring',
                year:               1665,
                museum:             'Mauritshuis, The Hague',
                technique:          'Oil on canvas',
                size:               '44.5cm × 39cm',
                description:        'A young woman with a mysterious gaze, wearing a large pearl earring.',
                acquisitionDate:    '1822',
                exhibitions:        ['Vermeer and the Delft School', 'The Golden Age of Dutch Painting'],
                restorations:       ['1991', '2018'],
                symbolism:          'The pearl earring may symbolize wealth, purity, and the passage of youth.',
                image:              'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Girl_with_a_Pearl_Earring_-_Johannes_Vermeer_-_National_Gallery_of_Art_2014.5.1.jpg/1200px-Girl_with_a_Pearl_Earring_-_Johannes_Vermeer_-_National_Gallery_of_Art_2014.5.1.jpg'},
               {title:              'View of Delft',
                year:               1660,
                museum:             'Mauritshuis, The Hague',
                technique:          'Oil on canvas',
                size:               '98.5cm × 133cm',
                description:        "A panoramic view of Delft, Vermeer's hometown, showcasing its architecture and daily life.",
                acquisitionDate:    '1822',
                exhibitions:        ['Dutch Golden Age Paintings'],
                restorations:       ['1970'],
                symbolism:          "The view may represent Vermeer's pride in his hometown and the Dutch Golden Age.",
                image:              'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Johannes_Vermeer_-_View_of_Delft_-_National_Gallery_of_Art_2014.5.2.jpg/1200px-Johannes_Vermeer_-_View_of_Delft_-_National_Gallery_of_Art_2014.5.2.jpg'},
               {title:              'The Milkmaid',
                year:               1658,
                museum:             'Rijksmuseum, Amsterdam',
                technique:          'Oil on canvas',
                size:               '45.8cm × 41cm',
                description:        'A simple domestic scene of a young woman pouring milk into a pitcher.',
                acquisitionDate:    '1817',
                exhibitions:        ['Dutch Masters'],
                restorations:       ['1994'],
                symbolism:          'The milkmaid may symbolize everyday life, simplicity, and the importance of light.',
                image:              'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Johannes_Vermeer_-_The_Milkmaid_-_National_Gallery_of_Art_2014.5.3.jpg/1200px-Johannes_Vermeer_-_The_Milkmaid_-_National_Gallery_of_Art_2014.5.3.jpg'},
               {title:              'The Geographer',
                year:               1669,
                museum:             'Louvre, Paris',
                technique:          'Oil on canvas',
                size:               '51.5cm × 45.5cm',
                description:        'A man studying a globe, representing intellectual curiosity and exploration.',
                acquisitionDate:    '1817',
                exhibitions:        ['Vermeer and the Delft School', 'The Golden Age of Dutch Painting'],
                restorations:       ['1991', '2018'],
                symbolism:          'The globe may symbolize knowledge, discovery, and the interconnectedness of the world.',
                image:              'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Johannes_Vermeer_-_The_Geographer_-_National_Gallery_of_Art_2014.5.4.jpg/1200px-Johannes_Vermeer_-_The_Geographer_-_National_Gallery_of_Art_2014.5.4.jpg'},
               {title:              'Woman Reading a Letter',
                year:               1665,
                museum:             'National Gallery of Art, Washington, D.C.',
                technique:          'Oil on canvas',
                size:               '77.5cm × 65cm',
                description:        'A woman absorbed in reading a letter, conveying a sense of intimacy and contemplation.',
                acquisitionDate:    '1962',
                exhibitions:        ['Vermeer: The Master of Delft'],
                restorations:       ['1992'],
                symbolism:          'The letter may symbolize communication, longing, and the power of words.',
                image:              'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Johannes_Vermeer_-_Woman_Reading_a_Letter_-_National_Gallery_of_Art_2014.5.5.jpg/1200px-Johannes_Vermeer_-_Woman_Reading_a_Letter_-_National_Gallery_of_Art_2014.5.5.jpg'}];
